### Add a physical person to an event
POST http://localhost:8080/api/isikud/add-fyysiline-isik
Content-Type: application/json

{
  "eesnimi": "John",
  "perekonnanimi": "Doe",
  "isikukood": "38501029876",
  "maksmiseViis": "sularaha",
  "lisainfo": "Additional information about the physical person",
  "yritusId": 2
}

### Delete a physical person
GET http://localhost:8080/api/isikud/delete-fyysiline-isik?id=1
